config/routes.rb
Umove::Application.routes.draw do
  devise_for :users
  resources :juniors

  root 'juniors#index'

  

end

app/models/junior.rb
class Junior < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/juniors_controller.rb
class JuniorsController < ApplicationController
  before_action :set_junior, only: [:show, :edit, :update, :destroy]

  # GET /juniors
  # GET /juniors.json
  def index
    @juniors = Junior.all
  end

  # GET /juniors/1
  # GET /juniors/1.json
  def show
  end

  # GET /juniors/new
  def new
    @junior = Junior.new
  end

  # GET /juniors/1/edit
  def edit
  end

  # POST /juniors
  # POST /juniors.json
  def create
    @junior = Junior.new(junior_params)

    respond_to do |format|
      if @junior.save
        format.html { redirect_to @junior, notice: 'Junior was successfully created.' }
        format.json { render action: 'show', status: :created, location: @junior }
      else
        format.html { render action: 'new' }
        format.json { render json: @junior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /juniors/1
  # PATCH/PUT /juniors/1.json
  def update
    respond_to do |format|
      if @junior.update(junior_params)
        format.html { redirect_to @junior, notice: 'Junior was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @junior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /juniors/1
  # DELETE /juniors/1.json
  def destroy
    @junior.destroy
    respond_to do |format|
      format.html { redirect_to juniors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_junior
      @junior = Junior.find(params[:id])
      @title = "lalaal"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def junior_params
      params.require(:junior).permit(:name, :available)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/juniors_helper.rb
module JuniorsHelper
end

app/views/juniors/_form.html.erb
<%= form_for(@junior) do |f| %>
  <% if @junior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@junior.errors.count, "error") %> prohibited this junior from being saved:</h2>

      <ul>
      <% @junior.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-3 columns">
      <%= f.label :name, class: "right inline"%>
    </div>
    
    <div class="small-9 columns"><%= f.text_field :name %></div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :available , class: "right inline"%><br>
    </div>
    <div class="small-9 columns"> <%= f.check_box :available %></div> 
  </div>
  <div class="row">
    <div class="small-9 small-offset-3"><%= f.submit %></div>
  </div>
<% end %>

app/views/juniors/edit.html.erb
<h1>Editing junior</h1>

<%= render 'form' %>

<%= link_to 'Show', @junior %> |
<%= link_to 'Back', juniors_path %>

app/views/juniors/index.html.erb
<% content_for :title do %>
   Juniors
<% end %>
<h2><%= content_for :title %></h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Available</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @juniors.each do |junior| %>
      <tr>
        <td><%= junior.name %></td>
        <td><%= junior.available %></td>
        <td><%= link_to 'Show', junior %></td>
        <td><%= link_to 'Edit', edit_junior_path(junior) %></td>
        <td><%= link_to 'Destroy', junior, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Junior', new_junior_path %>

app/views/juniors/new.html.erb
<h1>New junior</h1>

<%= render 'form' %>

<%= link_to 'Back', juniors_path %>

app/views/juniors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @junior.name %>
</p>

<p>
  <strong>Available:</strong>
  <%= @junior.available %>
</p>

<%= link_to 'Edit', edit_junior_path(@junior) %> |
<%= link_to 'Back', juniors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "uMove", root_path %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <li class="divider"></li>
          <li><%= link_to "Something", "#" %> </li>
          <li class="divider"></li>
          <li><%= link_to "Other thing", "#" %></li>  
          <li class="divider"></li>
        </ul>
      </section>


    </nav>

    <div class="row">

      <div class="large-3 column">
        <h2>Sidebar</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat, iure.
      </div>
      <div class="large-9 columns"> 
          <%= yield %>
      </div>

    </div> 
    <%= javascript_include_tag "application" %>
  </body>
</html>